#!/usr/bin/env bash
set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

EXPECTED_FILES=(
  GPT-CONFIGURATION.md
  K01-FOUNDATION-AUTHORITY-STAGES-ADR-AUTOGOVERNANCE.md
  K02-PRODUCT-DELIVERY-SLICES-DAG-TRACEABILITY.md
  K03-ASYNC-GIT-PUBLICATION-RELEASE.md
  K04-ENGINEERING-TOOLKIT-PERSISTENCE-UAT.md
  K05-INSTALL-BUNDLE-PROCEDURE-PREFLIGHT.md
  K06-AI-ORCHESTRATION-PRODUCT-MODEL-USER-TIME.md
  K07-RESPONSES-SCOPE-VERSIONING-CHANGE-CONTROL.md
  K08-TEMPLATES-ADR-IMPLEMENTATION-PLAN.md
  K09-TEMPLATES-AUDIT-UAT-TRACEABILITY.md
  K10-PROVENANCE-ADOPTION-PACKAGING.md
  ADOPTION-RECORD.md
  ARAYA-AX3-v0.6.0-CANONICAL-AUDIT.md
)

for f in "${EXPECTED_FILES[@]}"; do
  [[ -f "$f" ]] || { echo "FAIL: missing canonical file: $f"; exit 1; }
done

sha256sum -c SHA256SUMS.txt

echo "CANONICAL_INTEGRITY=PASS"
echo "CANONICAL_FILES=13"
